name: Build - Pull Request
on:
  pull_request:
permissions:
  id-token: write
  contents: read
jobs:
  build:
    uses: "fpmi-hci-2023/project13b-chatgpt/.github/workflows/docker_build.yaml"
    secrets:
      gh_sudo_token: ${{ secrets.GH_SUDO_TOKEN }}
