name: Deployment - k8s

on:
  workflow_dispatch: # manual trigger
    inputs:
      build_src:
        description: "Src version to build. For GitTag: \"tag:[name]\", For GitBranch: \"branch:[name]\", For GitCommit: \"commit:[hash]\", For EcrTag: \"ecr:[tag]\", For PullRequest: \"pr:[number]\""
        required: false
        default: 'branch:main'

permissions:
  deployments: write
  id-token: write
  contents: read

jobs:
  build_and_push:
    uses: "fpmi-hci-2023/project13b-chatgpt/.github/workflows/docker_build_and_push.yaml@main"
    with:
      name: servicediscovery
      build_src: ${{ github.event.inputs.build_src }}
    secrets:
      gh_sudo_token: ${{ secrets.GH_SUDO_TOKEN }}
