name: "Run golangci-lint"

on:
  workflow_call:
    inputs:
      go_version:
        description: "Version of go runtime to install"
        type: string
        default: '1.21.1'
    secrets:
      gh_sudo_token:
      required: true

jobs:
  lint:
    name: "Run golangci-lint"
    runs-on: ubuntu-latest
    steps:
      - name: Git Fetch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check for go repo
        id: go_check
        run: |
          if [ -f "go.mod" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
      - name: Setup Git for Go
        run: git config --global url."https://git:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
        env:
          GITHUB_TOKEN: ${{ secrets.gh_sudo_token }}
      - name: Install Go
        uses: actions/setup-go@v4
        if: steps.go_check.outputs.exists == 'true'
        with:
          go-version: ${{ inputs.go_version }}
      - name: GolangCI Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: ${{ github.workspace }}
          args: --timeout=1m --config=${{ github.workspace }}/.golangci.yml --issues-exit-code=0
