name: "Deploy to Kubernetes"

on:
  workflow_call:
    inputs:
      serviceName:
        required: true
        type: string
    secrets:
      gh_sudo_token:
        required: true
      kubernetes_secret:
        required: true
      kubernetes_url:
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Git Fetch
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v3
        with:
          method: service-account
          k8s-url: ${{ secrets.kubernetes_url }}
          k8s-secret: ${{ secrets.kubernetes_secret }}
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 'v3.6.0'
      - name: Add Helm Repo
        run: helm repo add stable https://charts.helm.sh/stable
      - name: Update Helm Repo
        run: helm repo update
      - name: Deploy Helm Chart
        run: |
          helm upgrade --install ${{ inputs.serviceName }}-helm charts/${{ inputs.serviceName }} --namespace hci-helm \
          --set image.repository=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }} \
          --set image.tag=latest
